spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot02?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true